### ISSUE TITLE
OTA什么时候实现呢，没有OTA，实用性不够啊。

### ISSUE THREAD

**Issue by jieranzhi** [OpenAtomFoundation/TencentOS-tiny#129]
rt

**Comment by daishengdong** [comment]
coming soon

**Comment by lilechao** [comment]
rt+1

**Comment by Supowang1989** [comment]
请参考https://github.com/Tencent/TencentOS-tiny/blob/master/doc/21.OTA_Quick_Start_based_EVB_MX_Plus.md

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年
http://weibo.ws/zZNbxG
阿里云企业级服务器1折限时特惠
http://weibo.ws/SIyDRE
阿里云建站 速成美站 - 千套模板，价格低至500元
http://weibo.ws/yVQAYW
