### ISSUE TITLE
是否有对树莓派的支持？

### ISSUE THREAD

**Issue by Derekduke** [OpenAtomFoundation/TencentOS-tiny#234]
目前TencentOS-tiny是否有对任何版本的树莓派的支持？如果暂无但有计划支持，我是否有机会参与对树莓派的BSP开发？PS：甚至目前看到对Cortex-A系列的板子支持非常少，除了已有的支持之外，还需要开发者对哪些板子做内核移植或BSP外设开发或诸如TFlite Micro等推理框架的移植，可以提供一些建议吗？

**Comment by Supowang1989** [comment]
目前还没支持树莓派，您可以参与贡献，欢迎
