### ISSUE TITLE
components/fs/kv/tos_kv.c中内存泄漏问题

### ISSUE THREAD

**Issue by tluio** [OpenAtomFoundation/TencentOS-tiny#258]
在tos_kv.c中发现了一些疑似内存泄漏的问题，不知道是否可以触发，建议检查一下
1、如果第344行和340行的if语句都为假，第329行为prev_key申请的内存会泄露
2、如果621行的item_out为NULL，并且从624行返回的话，第571行为item申请的内存以及第261行为kv_buf申请的内存会泄露

**Comment by Supowang1989** [comment]
感谢指出，我们近期修复

**Comment by tluio** [comment]
应该的，不客气！[228](https://github.com/Tencent/TencentOS-tiny/issues/228)也报告了一些疑似的内存泄漏问题，因为error handling code没处理好，您也可以一起看一下。

**Comment by daishengdong** [comment]
眼很尖！我马上提交修复
