### ISSUE TITLE
SAL层的AT架构好像不是线程安全的

### ISSUE THREAD

**Issue by HallwayZ** [OpenAtomFoundation/TencentOS-tiny#339]
int tos_at_cmd_exec(at_agent_t *at_agent, at_echo_t *echo, uint32_t timeout, const char *cmd, ...)
{
    int ret = 0;
    va_list args;

    if (!echo)
    {
        return -1;
    }

    if (tos_sem_create(&echo->__status_set_notify, 0) != K_ERR_NONE)
    {
        return -1;
    }

    at_echo_attach(at_agent, echo);

    va_start(args, cmd);
    ret = at_cmd_do_exec(at_agent, cmd, args);
    va_end(args);

    if (ret != 0)
    {
        at_agent->echo = K_NULL;
        return -1;
    }

    if (tos_sem_pend(&echo->__status_set_notify, tos_millisec2tick(timeout)) != K_ERR_NONE)
    {
        ret = -1;
    }

    tos_sem_destroy(&echo->__status_set_notify);

    at_agent->echo = K_NULL;

    return ret;
}

int esp8266_connect(const char *ip, const char *port, sal_proto_t proto)
{
    int id;
    at_echo_t echo;

    id = tos_at_channel_alloc(AT_AGENT, ip, port);
    if (id == -1)
    {
        return -1;
    }

    tos_at_echo_create(&echo, NULL, 0, NULL);
#if TOS_CFG_MODULE_SINGLE_LINK_EN > 0u
    tos_at_cmd_exec(&echo, 10000,
                    "AT+CIPSTART=\"%s\",\"%s\",%s\r\n",
                    proto == TOS_SAL_PROTO_UDP ? "UDP" : "TCP", ip, port);
#else
    tos_at_cmd_exec(AT_AGENT, &echo, 10000,
                    "AT+CIPSTART=%d,\"%s\",\"%s\",%s\r\n",
                    id, proto == TOS_SAL_PROTO_UDP ? "UDP" : "TCP", ip, port);
#endif
    if (echo.status == AT_ECHO_STATUS_OK)
    {
        return id;
    }

    tos_at_channel_free(AT_AGENT, id);

    return -1;
}

////////
如上的代码片段，像connect函数，多线程调用的话，at_echo_attach(at_agent, echo)的赋值会被覆盖掉导致解析数据的时候接收不到吧？

**Comment by Mculover666** [comment]
谢谢指出，这里确实会引发线程不安全问题，AT框架设计了global_lock来锁at_agent全局变量，我优化之后提交

**Comment by Mculover666** [comment]
已修复：[https://github.com/OpenAtomFoundation/TencentOS-tiny/commit/87fd8e839d042163954acb4365684a5401039840](https://github.com/OpenAtomFoundation/TencentOS-tiny/commit/87fd8e839d042163954acb4365684a5401039840)
