### ISSUE TITLE
Driver_USBH.c文件中有大量函数为空，疑似缺失漏写，是否需要完善？

### ISSUE THREAD

**Issue by lxqyyds** [OpenAtomFoundation/TencentOS-tiny#361]
https://github.com/OpenAtomFoundation/TencentOS-tiny/blob/master/platform/vendor_bsp/nxp/MIMXRT1062/CMSIS/Driver/DriverTemplates/Driver_USBH.c#L55
代码网址如上

**Comment by Supowang1989** [comment]
驱动库的代码使用的nxp官方的程序，原则上我们不直接维护，只会定期升级，建议反馈到芯片厂商nxp
