### ISSUE TITLE
AWTK 针对腾讯 TencentOS-tiny 的移植

### ISSUE THREAD

**Issue by xianjimli** [OpenAtomFoundation/TencentOS-tiny#59]
AWTK 针对腾讯 TencentOS-tiny 的移植: https://github.com/zlgopen/awtk-stm32f103ze-tencentos

**Comment by daishengdong** [comment]
cool !

**Comment by cleanupcrashanrjank** [comment]
赞

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xianjimli** [comment]
刚加一个了新项目：https://github.com/zlgopen/awtk-stm32h743iitx-tencentos

提供了如下功能：

* 集成实时操作系统 (RTOS)（腾讯的 TinyOS)
* 集成 FATFS 文件系统，访问 SD 卡的数据。
* 实现从文件系统加载应用程序的资源。

完整移植文档：https://github.com/zlgopen/awtk-stm32h743iitx-tencentos/blob/master/docs/stm32h743iitx_port.md

**Comment by Supowang1989** [comment]
感谢支持，能否基于TencentOS Tiny的主仓提供一个版本，您这个项目使用的TencentOS Tiny内核是老版本了

**Comment by xianjimli** [comment]
谢谢提醒，已更新。
