### ISSUE TITLE
如何编译内核代码？

### ISSUE THREAD

**Issue by XidianGeneral** [OpenAtomFoundation/TencentOS-tiny#75]
Linux内核代码在x86平台上编译可以用make menuconfig和make之类的命令，但是该内核源码没有发现Makefile。所以请问应该如何编译该内核代码？

**Comment by daishengdong** [comment]
您日常使用的嵌入式开发工具是什么？

**Comment by XidianGeneral** [comment]
我一直都是用gcc或者clang在x86平台上编译和测试Linux内核代码，但是没有在其他架构（如ARM）上编译过Linux内核代码

**Comment by daishengdong** [comment]
您客气了。

目前我们系统做了大量的sample工程之类，主要还是基于keil、IAR这类传统常用的MCU级别嵌入式开发IDE工具，目前还没有一个能贯穿整体模块的makefile体系及menuconfig构建（这也确实是现阶段我们所欠缺的）。

不过针对您的诉求，我们也提供了gcc+makefile开发工具链的构建demo，譬如：
`https://github.com/Tencent/TencentOS-tiny/tree/master/board/TencentOS_tiny_EVB_MX_Plus/GCC/hello_world`

在此工程目录下make可以直接编译hello_world工程（实际上，每个板子目录下，GCC/KEIL/IAR分别对应了这三个工具链的样例编译工程，当然有的三个工具链都有，有的主要还是聚焦在最常用的keil工具链上，实际上对于IDE来说，IAR添加一个工程与keil是大同小异的），依赖的是arm-none-eabi-gcc交叉编译器（实际上，这个make工程也是我们通过stm32 cubeMX工具生成的，此工具可以生成上述三个编译工具链下的编译工程框架）。

也许您做linux内核开发，更为习惯的是GCC+makefile裸写代码的快感，但个人建议的话，MCU RTOS环境下开发，基于传统的嵌入式集成开发环境会更加友好（固件烧写、单步调试等会相对方便）。对于熟悉MCU级嵌入式开发的同学来说，在我们的sample工程基础上，增添一些自己需要的模块文件，删掉一些自己不需要的文件，相对来说是很简单的。

您有任何疑问或需要，欢迎加入我们的官方交流沟通QQ群或微信群，群二维码在github主页readme第八章。
